/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoDaForca;

/**
 *
 * @author Notebook
 */
public class Forca extends javax.swing.JFrame {

    /**
     * Creates new form Forca
     */
    public Forca(jogar j,String dica,String palavra,char[] vet) {
        initComponents();
        this.jogo=j;
        hint.setText(String.valueOf(dica));
    }
    jogar jogo;
    char[] vet;
    String dica,palavra;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Palavra = new javax.swing.JTextField();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        E = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        G = new javax.swing.JRadioButton();
        H = new javax.swing.JRadioButton();
        I = new javax.swing.JRadioButton();
        J = new javax.swing.JRadioButton();
        K = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        W = new javax.swing.JRadioButton();
        M = new javax.swing.JRadioButton();
        N = new javax.swing.JRadioButton();
        O = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        Q = new javax.swing.JRadioButton();
        R = new javax.swing.JRadioButton();
        S = new javax.swing.JRadioButton();
        T = new javax.swing.JRadioButton();
        U = new javax.swing.JRadioButton();
        V = new javax.swing.JRadioButton();
        X = new javax.swing.JRadioButton();
        nove = new javax.swing.JRadioButton();
        Y = new javax.swing.JRadioButton();
        Z = new javax.swing.JRadioButton();
        zero = new javax.swing.JRadioButton();
        um = new javax.swing.JRadioButton();
        dois = new javax.swing.JRadioButton();
        tres = new javax.swing.JRadioButton();
        quatro = new javax.swing.JRadioButton();
        cinco = new javax.swing.JRadioButton();
        seis = new javax.swing.JRadioButton();
        sete = new javax.swing.JRadioButton();
        oito = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        hint = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Palavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalavraActionPerformed(evt);
            }
        });

        buttonGroup1.add(A);
        A.setText("A");

        buttonGroup1.add(B);
        B.setText("B");

        buttonGroup1.add(C);
        C.setText("C");

        buttonGroup1.add(D);
        D.setText("D");

        buttonGroup1.add(E);
        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        buttonGroup1.add(F);
        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });

        buttonGroup1.add(G);
        G.setText("G");

        buttonGroup1.add(H);
        H.setText("H");

        buttonGroup1.add(I);
        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        buttonGroup1.add(J);
        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });

        buttonGroup1.add(K);
        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });

        buttonGroup1.add(L);
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });

        buttonGroup1.add(W);
        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });

        buttonGroup1.add(M);
        M.setText("M");

        buttonGroup1.add(N);
        N.setText("N");

        buttonGroup1.add(O);
        O.setText("O");

        buttonGroup1.add(P);
        P.setText("P");

        buttonGroup1.add(Q);
        Q.setText("Q");

        buttonGroup1.add(R);
        R.setText("R");

        buttonGroup1.add(S);
        S.setText("S");

        buttonGroup1.add(T);
        T.setText("T");

        buttonGroup1.add(U);
        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });

        buttonGroup1.add(V);
        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });

        buttonGroup1.add(X);
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        buttonGroup1.add(nove);
        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        buttonGroup1.add(Y);
        Y.setText("Y");

        buttonGroup1.add(Z);
        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });

        buttonGroup1.add(zero);
        zero.setText("0");

        buttonGroup1.add(um);
        um.setText("1");

        buttonGroup1.add(dois);
        dois.setText("2");

        buttonGroup1.add(tres);
        tres.setText("3");

        buttonGroup1.add(quatro);
        quatro.setText("4");

        buttonGroup1.add(cinco);
        cinco.setText("5");

        buttonGroup1.add(seis);
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        buttonGroup1.add(sete);
        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        buttonGroup1.add(oito);
        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        jLabel1.setText("Dica:");

        hint.setEditable(false);
        hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintActionPerformed(evt);
            }
        });

        jLabel2.setText("Já Sabe? Pode arriscar aqui ->");

        yes.setText("Confima a letra?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hint)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A)
                                .addGap(18, 18, 18)
                                .addComponent(B)
                                .addGap(18, 18, 18)
                                .addComponent(C)
                                .addGap(18, 18, 18)
                                .addComponent(D)
                                .addGap(18, 18, 18)
                                .addComponent(E))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(M)
                                        .addGap(18, 18, 18)
                                        .addComponent(N)
                                        .addGap(18, 18, 18)
                                        .addComponent(O)
                                        .addGap(18, 18, 18)
                                        .addComponent(P))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Y)
                                        .addGap(18, 18, 18)
                                        .addComponent(Z)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(zero)
                                        .addGap(18, 18, 18)
                                        .addComponent(um)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dois)
                                    .addComponent(Q))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(F)
                                .addGap(24, 24, 24)
                                .addComponent(G)
                                .addGap(18, 18, 18)
                                .addComponent(H)
                                .addGap(18, 18, 18)
                                .addComponent(I)
                                .addGap(18, 18, 18)
                                .addComponent(J)
                                .addGap(18, 18, 18)
                                .addComponent(K)
                                .addGap(18, 18, 18)
                                .addComponent(L))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tres)
                                .addGap(26, 26, 26)
                                .addComponent(quatro)
                                .addGap(18, 18, 18)
                                .addComponent(cinco)
                                .addGap(18, 18, 18)
                                .addComponent(seis)
                                .addGap(18, 18, 18)
                                .addComponent(sete)
                                .addGap(18, 18, 18)
                                .addComponent(oito)
                                .addGap(18, 18, 18)
                                .addComponent(nove))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(R)
                                .addGap(18, 18, 18)
                                .addComponent(S)
                                .addGap(18, 18, 18)
                                .addComponent(T)
                                .addGap(18, 18, 18)
                                .addComponent(U)
                                .addGap(18, 18, 18)
                                .addComponent(V)
                                .addGap(18, 18, 18)
                                .addComponent(X)
                                .addGap(18, 18, 18)
                                .addComponent(W))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(yes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C)
                    .addComponent(D)
                    .addComponent(I)
                    .addComponent(J)
                    .addComponent(K)
                    .addComponent(L)
                    .addComponent(H)
                    .addComponent(G)
                    .addComponent(F)
                    .addComponent(E))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M)
                    .addComponent(N)
                    .addComponent(O)
                    .addComponent(P)
                    .addComponent(U)
                    .addComponent(V)
                    .addComponent(X)
                    .addComponent(W)
                    .addComponent(T)
                    .addComponent(S)
                    .addComponent(R)
                    .addComponent(Q))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Y)
                    .addComponent(Z)
                    .addComponent(zero)
                    .addComponent(um)
                    .addComponent(seis)
                    .addComponent(sete)
                    .addComponent(oito)
                    .addComponent(nove)
                    .addComponent(cinco)
                    .addComponent(quatro)
                    .addComponent(tres)
                    .addComponent(dois))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalavraActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noveActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seteActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oitoActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZActionPerformed

    private void hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintActionPerformed
        // TODO add your handling code here:
        hint.setText(String.valueOf(dica));
    }//GEN-LAST:event_hintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forca().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JRadioButton E;
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton G;
    private javax.swing.JRadioButton H;
    private javax.swing.JRadioButton I;
    private javax.swing.JRadioButton J;
    private javax.swing.JRadioButton K;
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton M;
    private javax.swing.JRadioButton N;
    private javax.swing.JRadioButton O;
    private javax.swing.JRadioButton P;
    private javax.swing.JTextField Palavra;
    private javax.swing.JRadioButton Q;
    private javax.swing.JRadioButton R;
    private javax.swing.JRadioButton S;
    private javax.swing.JRadioButton T;
    private javax.swing.JRadioButton U;
    private javax.swing.JRadioButton V;
    private javax.swing.JRadioButton W;
    private javax.swing.JRadioButton X;
    private javax.swing.JRadioButton Y;
    private javax.swing.JRadioButton Z;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cinco;
    private javax.swing.JRadioButton dois;
    private javax.swing.JTextField hint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton nove;
    private javax.swing.JRadioButton oito;
    private javax.swing.JRadioButton quatro;
    private javax.swing.JRadioButton seis;
    private javax.swing.JRadioButton sete;
    private javax.swing.JRadioButton tres;
    private javax.swing.JRadioButton um;
    private javax.swing.JButton yes;
    private javax.swing.JRadioButton zero;
    // End of variables declaration//GEN-END:variables
}
